<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net5.0</TargetFramework>
		<ApplicationIcon>Assets/avalonia-logo.ico</ApplicationIcon>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
		<SuppressTfmSupportBuildWarnings>True</SuppressTfmSupportBuildWarnings>
		<NoWarn>$(NoWarn);NETSDK1138</NoWarn>
	</PropertyGroup>

	<Import Project="../../build/avalonia.props" />

	<ItemGroup>
		<PackageReference Include="Sortable.Avalonia" Version="2.0.1" />
		<ProjectReference Include="../../src/ReCap.CommonUI/ReCap.CommonUI.csproj" />
    </ItemGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets/**/*.ico" />
		<AvaloniaResource Include="Assets/**/*.ttf" />
	</ItemGroup>
</Project>
