name: Release

on:
  push:
    tags: ['v*']

jobs:
  publish:
    uses: Resurrection-Capsule/.github/.github/workflows/dotnet-nuget.yml@v1
    with:
      project: src/ReCap.CommonUI/ReCap.CommonUI.csproj
    secrets: inherit
